#  ____  _                _                  _ __  __ _ _
# / ___|| |__   ___ _ __ | |__   ___ _ __ __| |  \/  (_) | _____
# \___ \| '_ \ / _ \ '_ \| '_ \ / _ \ '__/ _` | |\/| | | |/ / _ \
#  ___) | | | |  __/ |_) | | | |  __/ | | (_| | |  | | |   <  __/
# |____/|_| |_|\___| .__/|_| |_|\___|_|  \__,_|_|  |_|_|_|\_\___|
#                  |_|



FROM alpine:3.20



RUN apk add --no-cache bash postgresql-client
      # pici image ami tartalmaz bash-t es postgrest!


COPY scripts/startup.sh /scripts/startup.sh
    # atmasoljuk sajat geprol a containerbe


RUN chmod +x /scripts/startup.sh
      # Futtatasi jogot (x = execute) adunk a programra


WORKDIR /workspace
